# Generated by Django 3.1.7 on 2021-02-26 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210224_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='tag',
            new_name='tags',
        ),
    ]
